# Generated by Django 4.1.5 on 2023-02-14 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'equipes',
            },
        ),
        migrations.CreateModel(
            name='TipoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_acesso',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.IntegerField(max_length=11)),
                ('equipes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.equipes')),
                ('tipo_acesso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipoacesso')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
